language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - export APP_SETTINGS="camputer.config.TestingConfig"
  - mkdir db
  - python create_db.py -c camputer.config.TestingConfig

script:
  - python manage.py test